// Emoji icon helper for ingredient chips. Purely presentational.

const EXACT: Record<string, string> = {
  rice: "🍚",
  egg: "🥚",
  eggs: "🥚",
  onion: "🧅",
  "red onion": "🧅",
  "green onion": "🌱",
  scallion: "🌱",
  shallot: "🧅",
  tomato: "🍅",
  "sun-dried tomatoes": "🍅",
  spinach: "🥬",
  kale: "🥬",
  lettuce: "🥬",
  cabbage: "🥬",
  paneer: "🧀",
  yogurt: "🥛",
  potato: "🥔",
  "sweet potato": "🍠",
  pasta: "🍝",
  gnocchi: "🍝",
  noodles: "🍜",
  chicken: "🍗",
  turkey: "🍗",
  duck: "🦆",
  "bell pepper": "🫑",
  pepper: "🫑",
  chili: "🌶️",
  chile: "🌶️",
  "chipotle in adobo": "🌶️",
  mushroom: "🍄",
  cheese: "🧀",
  parmesan: "🧀",
  cotija: "🧀",
  "queso fresco": "🧀",
  brie: "🧀",
  burrata: "🧀",
  halloumi: "🧀",
  feta: "🧀",
  mozzarella: "🧀",
  avocado: "🥑",
  lemon: "🍋",
  lime: "🍈",
  "coconut milk": "🥥",
  coconut: "🥥",
  "soy sauce": "🥢",
  "truffle oil": "🫒",
  "olive oil": "🫒",
  olive: "🫒",
  olives: "🫒",
  prosciutto: "🥓",
  bacon: "🥓",
  chorizo: "🌭",
  sausage: "🌭",
  "basil pesto": "🌿",
  basil: "🌿",
  cilantro: "🌿",
  parsley: "🌿",
  tarragon: "🌿",
  mint: "🌿",
  rosemary: "🌿",
  thyme: "🌿",
  oregano: "🌿",
  "crème fraîche": "🥛",
  cream: "🥛",
  milk: "🥛",
  butter: "🧈",
  "dijon mustard": "🌭",
  mustard: "🌭",
  "puff pastry": "🥐",
  pastry: "🥐",
  bread: "🍞",
  baguette: "🥖",
  flour: "🌾",
  wheat: "🌾",
  oats: "🌾",
  "black beans": "🫘",
  beans: "🫘",
  chickpeas: "🫘",
  lentils: "🫘",
  tofu: "⬜",
  "corn tortillas": "🌽",
  tortilla: "🫓",
  corn: "🌽",
  "miso paste": "🥣",
  miso: "🥣",
  sriracha: "🌶️",
  kimchi: "🥬",
  saffron: "🌼",
  capers: "🫒",
  anchovies: "🐟",
  "smoked paprika": "🌶️",
  paprika: "🌶️",
  fish: "🐟",
  salmon: "🐟",
  tuna: "🐟",
  cod: "🐟",
  shrimp: "🦐",
  prawn: "🦐",
  prawns: "🦐",
  crab: "🦀",
  lobster: "🦞",
  squid: "🦑",
  octopus: "🐙",
  beef: "🥩",
  steak: "🥩",
  pork: "🥩",
  lamb: "🥩",
  carrot: "🥕",
  broccoli: "🥦",
  cucumber: "🥒",
  zucchini: "🥒",
  eggplant: "🍆",
  garlic: "🧄",
  ginger: "🫚",
  apple: "🍎",
  banana: "🍌",
  strawberry: "🍓",
  blueberry: "🫐",
  blueberries: "🫐",
  grape: "🍇",
  grapes: "🍇",
  pineapple: "🍍",
  mango: "🥭",
  orange: "🍊",
  peach: "🍑",
  cherry: "🍒",
  cherries: "🍒",
  watermelon: "🍉",
  honey: "🍯",
  salt: "🧂",
  sugar: "🍬",
  chocolate: "🍫",
  coffee: "☕",
  tea: "🍵",
  wine: "🍷",
  beer: "🍺",
  water: "💧",
  nuts: "🥜",
  peanut: "🥜",
  almond: "🥜",
  walnut: "🥜",
  cashew: "🥜",
  sesame: "🌰",
};

const KEYWORD_FALLBACKS: Array<[string, string]> = [
  ["cheese", "🧀"],
  ["shrimp", "🦐"],
  ["prawn", "🦐"],
  ["fish", "🐟"],
  ["salmon", "🐟"],
  ["tuna", "🐟"],
  ["chicken", "🍗"],
  ["beef", "🥩"],
  ["pork", "🥩"],
  ["lamb", "🥩"],
  ["bacon", "🥓"],
  ["sausage", "🌭"],
  ["pepper", "🫑"],
  ["chili", "🌶️"],
  ["chile", "🌶️"],
  ["pepper flake", "🌶️"],
  ["onion", "🧅"],
  ["garlic", "🧄"],
  ["ginger", "🫚"],
  ["tomato", "🍅"],
  ["potato", "🥔"],
  ["mushroom", "🍄"],
  ["lettuce", "🥬"],
  ["spinach", "🥬"],
  ["cabbage", "🥬"],
  ["kale", "🥬"],
  ["carrot", "🥕"],
  ["broccoli", "🥦"],
  ["corn", "🌽"],
  ["bean", "🫘"],
  ["lentil", "🫘"],
  ["pea", "🫛"],
  ["egg", "🥚"],
  ["milk", "🥛"],
  ["cream", "🥛"],
  ["yogurt", "🥛"],
  ["butter", "🧈"],
  ["bread", "🍞"],
  ["pasta", "🍝"],
  ["noodle", "🍜"],
  ["rice", "🍚"],
  ["flour", "🌾"],
  ["oat", "🌾"],
  ["wheat", "🌾"],
  ["herb", "🌿"],
  ["basil", "🌿"],
  ["mint", "🌿"],
  ["cilantro", "🌿"],
  ["parsley", "🌿"],
  ["oil", "🫒"],
  ["olive", "🫒"],
  ["vinegar", "🍶"],
  ["sauce", "🥫"],
  ["paste", "🥫"],
  ["soy", "🥢"],
  ["miso", "🥣"],
  ["lemon", "🍋"],
  ["lime", "🍈"],
  ["apple", "🍎"],
  ["banana", "🍌"],
  ["berry", "🫐"],
  ["nut", "🥜"],
  ["seed", "🌰"],
  ["honey", "🍯"],
  ["sugar", "🍬"],
  ["salt", "🧂"],
  ["chocolate", "🍫"],
  ["wine", "🍷"],
  ["beer", "🍺"],
  ["coffee", "☕"],
  ["tea", "🍵"],
  ["tortilla", "🫓"],
  ["pastry", "🥐"],
  ["coconut", "🥥"],
];

export function getIngredientIcon(name: string): string {
  const key = name.trim().toLowerCase();
  if (!key) return "🥄";
  if (EXACT[key]) return EXACT[key];
  for (const [needle, icon] of KEYWORD_FALLBACKS) {
    if (key.includes(needle)) return icon;
  }
  return "🥄";
}