import jsPDF from "jspdf";
import type { Recipe } from "@/lib/recipes.functions";

const MARGIN = 48;
const LINE = 16;

export function downloadRecipePdf(recipe: Recipe) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxW = pageW - MARGIN * 2;
  let y = MARGIN;

  const ensureSpace = (h: number) => {
    if (y + h > pageH - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const writeLines = (text: string, size: number, style: "normal" | "bold" = "normal") => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, maxW) as string[];
    for (const line of lines) {
      ensureSpace(size + 4);
      doc.text(line, MARGIN, y);
      y += size + 4;
    }
  };

  const hr = () => {
    ensureSpace(12);
    doc.setDrawColor(200);
    doc.line(MARGIN, y, pageW - MARGIN, y);
    y += 12;
  };

  // Title
  writeLines(recipe.title, 22, "bold");
  y += 4;
  writeLines(recipe.blurb, 11);
  y += 6;

  // Servings — prominent
  const servings = recipe.servings ?? recipe.nutrition?.servings;
  if (servings) {
    writeLines(`Serves ${servings}`, 13, "bold");
    y += 2;
  }

  // Meta line
  const prep = recipe.prepTimeMinutes;
  const total = recipe.totalTimeMinutes;
  const meta: string[] = [];
  if (prep != null) meta.push(`Prep ${prep}m`);
  meta.push(`Cook ${recipe.cookTimeMinutes}m`);
  if (total != null) meta.push(`Total ${total}m`);
  meta.push(recipe.cuisine);
  if (recipe.difficulty) meta.push(`Difficulty: ${recipe.difficulty}`);
  if (recipe.dietary?.length) meta.push(recipe.dietary.join(" · "));
  writeLines(meta.join("   |   "), 10);
  hr();

  // Nutrition
  const n = recipe.nutrition?.perServing;
  if (n) {
    writeLines(
      `Nutrition (per serving${servings ? `, recipe makes ${servings})` : ")"}`,
      12,
      "bold",
    );
    const parts: string[] = [];
    if (n.calories != null) parts.push(`${n.calories} kcal`);
    if (n.proteinG != null) parts.push(`Protein ${n.proteinG}g`);
    if (n.carbsG != null) parts.push(`Carbs ${n.carbsG}g`);
    if (n.fatG != null) parts.push(`Fat ${n.fatG}g`);
    if (n.sugarG != null) parts.push(`Sugar ${n.sugarG}g`);
    if (n.fiberG != null) parts.push(`Fiber ${n.fiberG}g`);
    writeLines(parts.join("   ·   "), 11);
    y += 4;
    hr();
  }

  // Ingredients
  writeLines(
    `Ingredients${servings ? ` (for ${servings} serving${servings === 1 ? "" : "s"})` : ""}`,
    14,
    "bold",
  );
  const ingredients = [...recipe.usedIngredients, ...recipe.missingIngredients];
  for (const item of ingredients) {
    writeLines(`• ${item}`, 11);
  }
  if (recipe.substitutions?.length) {
    y += 4;
    writeLines("Substitutions", 12, "bold");
    for (const s of recipe.substitutions) writeLines(`• ${s}`, 11);
  }
  y += 6;
  hr();

  // Steps
  writeLines("Method", 14, "bold");
  const timings = recipe.stepTimings ?? [];
  recipe.steps.forEach((step, i) => {
    const t = timings[i] != null ? ` (${timings[i]}m)` : "";
    writeLines(`${i + 1}. ${step}${t}`, 11);
    y += 2;
  });

  // Footer
  y += 12;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(140);
  ensureSpace(12);
  doc.text("Generated by FridgeCuisine · fridgecuisine.com", MARGIN, pageH - 24);

  const slug = recipe.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60) || "recipe";
  doc.save(`${slug}.pdf`);
}