// 500 foods from around the world
export const worldFoods: { food: string; country: string }[] = [
  { food: 'Sushi', country: 'Japan' },
  { food: 'Ramen', country: 'Japan' },
  { food: 'Tempura', country: 'Japan' },
  { food: 'Kimchi', country: 'South Korea' },
  { food: 'Bibimbap', country: 'South Korea' },
  { food: 'Bulgogi', country: 'South Korea' },
  { food: 'Pad Thai', country: 'Thailand' },
  { food: 'Green Curry', country: 'Thailand' },
  { food: 'Tom Yum Soup', country: 'Thailand' },
  { food: 'Pho', country: 'Vietnam' },
  { food: 'Banh Mi', country: 'Vietnam' },
  { food: 'Spring Rolls', country: 'Vietnam' },
  { food: 'Butter Chicken', country: 'India' },
  { food: 'Biryani', country: 'India' },
  { food: 'Masala Dosa', country: 'India' },
  { food: 'Chole Bhature', country: 'India' },
  { food: 'Rogan Josh', country: 'India' },
  { food: 'Momos', country: 'Nepal' },
  { food: 'Dal Bhat', country: 'Nepal' },
  { food: 'Sel Roti', country: 'Nepal' },
  { food: 'Dumplings', country: 'China' },
  { food: 'Peking Duck', country: 'China' },
  { food: 'Kung Pao Chicken', country: 'China' },
  { food: 'Hot Pot', country: 'China' },
  { food: 'Fried Rice', country: 'China' },
  { food: 'Adobo', country: 'Philippines' },
  { food: 'Sinigang', country: 'Philippines' },
  { food: 'Lechon', country: 'Philippines' },
  { food: 'Nasi Goreng', country: 'Indonesia' },
  { food: 'Satay', country: 'Indonesia' },
  { food: 'Rendang', country: 'Indonesia' },
  { food: 'Laksa', country: 'Malaysia' },
  { food: 'Nasi Lemak', country: 'Malaysia' },
  { food: 'Hainanese Chicken Rice', country: 'Singapore' },
  { food: 'Chili Crab', country: 'Singapore' },
  { food: 'Kebabs', country: 'Turkey' },
  { food: 'Baklava', country: 'Turkey' },
  { food: 'Lahmacun', country: 'Turkey' },
  { food: 'Shawarma', country: 'Lebanon' },
  { food: 'Hummus', country: 'Lebanon' },
  { food: 'Falafel', country: 'Egypt' },
  { food: 'Koshari', country: 'Egypt' },
  { food: 'Couscous', country: 'Morocco' },
  { food: 'Tagine', country: 'Morocco' },
  { food: 'Bunny Chow', country: 'South Africa' },
  { food: 'Bobotie', country: 'South Africa' },
  { food: 'Jollof Rice', country: 'Nigeria' },
  { food: 'Egusi Soup', country: 'Nigeria' },
  { food: 'Waakye', country: 'Ghana' },
  { food: 'Fufu', country: 'Ghana' },
  { food: 'Paella', country: 'Spain' },
  { food: 'Tapas', country: 'Spain' },
  { food: 'Churros', country: 'Spain' },
  { food: 'Pizza Margherita', country: 'Italy' },
  { food: 'Lasagna', country: 'Italy' },
  { food: 'Risotto', country: 'Italy' },
  { food: 'Gelato', country: 'Italy' },
  { food: 'Carbonara', country: 'Italy' },
  { food: 'Croissant', country: 'France' },
  { food: 'Ratatouille', country: 'France' },
  { food: 'Coq au Vin', country: 'France' },
  { food: 'Escargot', country: 'France' },
  { food: 'Fish and Chips', country: 'United Kingdom' },
  { food: 'Shepherd\'s Pie', country: 'United Kingdom' },
  { food: 'Full English Breakfast', country: 'United Kingdom' },
  { food: 'Haggis', country: 'Scotland' },
  { food: 'Welsh Rarebit', country: 'Wales' },
  { food: 'Irish Stew', country: 'Ireland' },
  { food: 'Sauerbraten', country: 'Germany' },
  { food: 'Bratwurst', country: 'Germany' },
  { food: 'Schnitzel', country: 'Austria' },
  { food: 'Fondue', country: 'Switzerland' },
  { food: 'Goulash', country: 'Hungary' },
  { food: 'Pierogi', country: 'Poland' },
  { food: 'Borscht', country: 'Ukraine' },
  { food: 'Cevapi', country: 'Bosnia and Herzegovina' },
  { food: 'Moussaka', country: 'Greece' },
  { food: 'Souvlaki', country: 'Greece' },
  { food: 'Tzatziki', country: 'Greece' },
  { food: 'Feijoada', country: 'Brazil' },
  { food: 'Pão de Queijo', country: 'Brazil' },
  { food: 'Brigadeiro', country: 'Brazil' },
  { food: 'Empanadas', country: 'Argentina' },
  { food: 'Asado', country: 'Argentina' },
  { food: 'Chimichurri Steak', country: 'Argentina' },
  { food: 'Ceviche', country: 'Peru' },
  { food: 'Lomo Saltado', country: 'Peru' },
  { food: 'Arepas', country: 'Venezuela' },
  { food: 'Bandeja Paisa', country: 'Colombia' },
  { food: 'Pupusas', country: 'El Salvador' },
  { food: 'Tacos', country: 'Mexico' },
  { food: 'Enchiladas', country: 'Mexico' },
  { food: 'Guacamole', country: 'Mexico' },
  { food: 'Mole Poblano', country: 'Mexico' },
  { food: 'Poutine', country: 'Canada' },
  { food: 'Lobster Roll', country: 'United States' },
  { food: 'Cheeseburger', country: 'United States' },
  { food: 'Barbecue Ribs', country: 'United States' },
  { food: 'Gumbo', country: 'United States' },
  { food: 'Clam Chowder', country: 'United States' },
  { food: 'Jerk Chicken', country: 'Jamaica' },
  { food: 'Ackee and Saltfish', country: 'Jamaica' },
  { food: 'Roti', country: 'Trinidad and Tobago' },
  { food: 'Curry Goat', country: 'Trinidad and Tobago' },
  { food: 'Bangers and Mash', country: 'England' },
  { food: 'Yorkshire Pudding', country: 'England' },
  { food: 'Smørrebrød', country: 'Denmark' },
  { food: 'Frikadeller', country: 'Denmark' },
  { food: 'Swedish Meatballs', country: 'Sweden' },
  { food: 'Gravlax', country: 'Sweden' },
  { food: 'Lutefisk', country: 'Norway' },
  { food: 'Reindeer Stew', country: 'Norway' },
  { food: 'Karelian Pies', country: 'Finland' },
  { food: 'Stroopwafel', country: 'Netherlands' },
  { food: 'Bitterballen', country: 'Netherlands' },
  { food: 'Belgian Waffles', country: 'Belgium' },
  { food: 'Moules-Frites', country: 'Belgium' },
  { food: 'Gnocchi', country: 'Italy' },
  { food: 'Ravioli', country: 'Italy' },
  { food: 'Tiramisu', country: 'Italy' },
  { food: 'Cassoulet', country: 'France' },
  { food: 'Crêpes', country: 'France' },
  { food: 'Pašticada', country: 'Croatia' },
  { food: 'SarmaSerbia125Ćevapi', country: 'Serbia' },
  { food: 'Shakshuka', country: 'Tunisia' },
  { food: 'Injera', country: 'Ethiopia' },
  { food: 'Doro Wat', country: 'Ethiopia' },
  { food: 'Suya', country: 'Nigeria' },
  { food: 'Biltong', country: 'South Africa' },
  { food: 'Matoke', country: 'Uganda' },
  { food: 'Nyama Choma', country: 'Kenya' },
  { food: 'Kibbeh', country: 'Lebanon' },
  { food: 'Mansaf', country: 'Jordan' },
  { food: 'Kabsa', country: 'Saudi Arabia' },
  { food: 'Machboos', country: 'Bahrain' },
  { food: 'Dolma', country: 'Armenia' },
  { food: 'Khachapuri', country: 'Georgia' },
  { food: 'Plov', country: 'Uzbekistan' },
  { food: 'Lagman', country: 'Kazakhstan' },
  { food: 'Manty', country: 'Kyrgyzstan' },
  { food: 'Beshbarmak', country: 'Kazakhstan' },
  { food: 'Pelmeni', country: 'Russia' },
  { food: 'Olivier Salad', country: 'Russia' },
  { food: 'Blini', country: 'Russia' },
  { food: 'Chicken Kyiv', country: 'Ukraine' },
  { food: 'Gibanica', country: 'Serbia' },
  { food: 'Shopska Salad', country: 'Bulgaria' },
  { food: 'Saganaki', country: 'Greece' },
  { food: 'Halloumi', country: 'Cyprus' },
  { food: 'Fesenjan', country: 'Iran' },
  { food: 'Ghormeh Sabzi', country: 'Iran' },
  { food: 'Nihari', country: 'Pakistan' },
  { food: 'Haleem', country: 'Pakistan' },
  { food: 'Kottu Roti', country: 'Sri Lanka' },
  { food: 'Hoppers', country: 'Sri Lanka' },
  { food: 'Thukpa', country: 'Tibet' },
  { food: 'Yak Butter Tea', country: 'Tibet' },
  { food: 'Bao Buns', country: 'China' },
  { food: 'Char Siu', country: 'Hong Kong' },
  { food: 'Egg Tarts', country: 'Macau' },
  { food: 'Bubble Tea', country: 'Taiwan' },
  { food: 'Oyster Omelette', country: 'Taiwan' },
  { food: 'Beef Noodle Soup', country: 'Taiwan' },
  { food: 'Okonomiyaki', country: 'Japan' },
  { food: 'Takoyaki', country: 'Japan' },
  { food: 'Yakitori', country: 'Japan' },
  { food: 'Katsu Curry', country: 'Japan' },
  { food: 'Tteokbokki', country: 'South Korea' },
  { food: 'Japchae', country: 'South Korea' },
  { food: 'Som Tam', country: 'Thailand' },
  { food: 'Massaman Curry', country: 'Thailand' },
  { food: 'Bún Chả', country: 'Vietnam' },
  { food: 'Cao Lầu', country: 'Vietnam' },
  { food: 'Char Kway Teow', country: 'Malaysia' },
  { food: 'Mee Goreng', country: 'Malaysia' },
  { food: 'Sisig', country: 'Philippines' },
  { food: 'Kare-Kare', country: 'Philippines' },
  { food: 'Bánh Xèo', country: 'Vietnam' },
  { food: 'Samosa', country: 'India' },
  { food: 'Pav Bhaji', country: 'India' },
  { food: 'Tandoori Chicken', country: 'India' },
  { food: 'Pani Puri', country: 'India' },
  { food: 'Gulab Jamun', country: 'India' },
  { food: 'Jalebi', country: 'India' },
  { food: 'Dhindo', country: 'Nepal' },
  { food: 'Yomari', country: 'Nepal' },
  { food: 'Apple Pie', country: 'United States' },
  { food: 'Buffalo Wings', country: 'United States' },
  { food: 'Cornbread', country: 'United States' },
  { food: 'Maple Syrup Pancakes', country: 'Canada' },
  { food: 'Tourtière', country: 'Canada' },
  { food: 'Alfajores', country: 'Argentina' },
  { food: 'Moqueca', country: 'Brazil' },
  { food: 'Chivito', country: 'Uruguay' },
  { food: 'Sopaipillas', country: 'Chile' },
  { food: 'Ajiaco', country: 'Colombia' },
  { food: 'Tamales', country: 'Guatemala' },
  { food: 'Gallo Pinto', country: 'Costa Rica' },
  { food: 'Arroz con Pollo', country: 'Cuba' },
  { food: 'Fajitas', country: 'Mexico' },
  { food: 'Quesadilla', country: 'Mexico' },
  { food: 'Pozole', country: 'Mexico' },
  { food: 'Chiles Rellenos', country: 'Mexico' },
  { food: 'Birria', country: 'Mexico' },
  { food: 'Udon', country: 'Japan' },
  { food: 'Onigiri', country: 'Japan' },
  { food: 'Sukiyaki', country: 'Japan' },
  { food: 'Oyakodon', country: 'Japan' },
  { food: 'Karaage', country: 'Japan' },
  { food: 'Samgyeopsal', country: 'South Korea' },
  { food: 'Sundubu Jjigae', country: 'South Korea' },
  { food: 'Galbi', country: 'South Korea' },
  { food: 'Khao Soi', country: 'Thailand' },
  { food: 'Pad See Ew', country: 'Thailand' },
  { food: 'Mango Sticky Rice', country: 'Thailand' },
  { food: 'Goi Cuon', country: 'Vietnam' },
  { food: 'Com Tam', country: 'Vietnam' },
  { food: 'Rendang Daging', country: 'Indonesia' },
  { food: 'Soto Ayam', country: 'Indonesia' },
  { food: 'Gado-Gado', country: 'Indonesia' },
  { food: 'Ayam Penyet', country: 'Indonesia' },
  { food: 'Mee Siam', country: 'Singapore' },
  { food: 'Kaya Toast', country: 'Singapore' },
  { food: 'Satay Bee Hoon', country: 'Singapore' },
  { food: 'Paneer Tikka', country: 'India' },
  { food: 'Rajma Chawal', country: 'India' },
  { food: 'Vada Pav', country: 'India' },
  { food: 'Kheer', country: 'India' },
  { food: 'Rasgulla', country: 'India' },
  { food: 'Aloo Paratha', country: 'India' },
  { food: 'Chicken Tikka Masala', country: 'India' },
  { food: 'Vindaloo', country: 'India' },
  { food: 'Pakora', country: 'India' },
  { food: 'Litti Chokha', country: 'India' },
  { food: 'Sekuwa', country: 'Nepal' },
  { food: 'Chatamari', country: 'Nepal' },
  { food: 'Gundruk', country: 'Nepal' },
  { food: 'Sekuwa', country: 'Nepal' },
  { food: 'Pirozhki', country: 'Russia' },
  { food: 'Solyanka', country: 'Russia' },
  { food: 'Beef Stroganoff', country: 'Russia' },
  { food: 'Khinkali', country: 'Georgia' },
  { food: 'Chak-Chak', country: 'Kazakhstan' },
  { food: 'Samsa', country: 'Uzbekistan' },
  { food: 'Shashlik', country: 'Azerbaijan' },
  { food: 'Harira', country: 'Morocco' },
  { food: 'Bastilla', country: 'Morocco' },
  { food: 'Mafe', country: 'Senegal' },
  { food: 'Yassa Chicken', country: 'Senegal' },
  { food: 'Peri Peri Chicken', country: 'Mozambique' },
  { food: 'Kapenta', country: 'Zimbabwe' },
  { food: 'Sadza', country: 'Zimbabwe' },
  { food: 'Tilapia Stew', country: 'Tanzania' },
  { food: 'Bunny Tea', country: 'Mauritius' },
  { food: 'Pastel de Nata', country: 'Portugal' },
  { food: 'Bacalhau', country: 'Portugal' },
  { food: 'Francesinha', country: 'Portugal' },
  { food: 'Pa amb Tomàquet', country: 'Spain' },
  { food: 'Gazpacho', country: 'Spain' },
  { food: 'Tortilla Española', country: 'Spain' },
  { food: 'Arancini', country: 'Italy' },
  { food: 'Ossobuco', country: 'Italy' },
  { food: 'Focaccia', country: 'Italy' },
  { food: 'Pesto Pasta', country: 'Italy' },
  { food: 'Cannoli', country: 'Italy' },
  { food: 'Bouillabaisse', country: 'France' },
  { food: 'Quiche Lorraine', country: 'France' },
  { food: 'Macarons', country: 'France' },
  { food: 'Baguette Sandwich', country: 'France' },
  { food: 'Steak Frites', country: 'France' },
  { food: 'Currywurst', country: 'Germany' },
  { food: 'Pretzel', country: 'Germany' },
  { food: 'Black Forest Cake', country: 'Germany' },
  { food: 'Rösti', country: 'Switzerland' },
  { food: 'Raclette', country: 'Switzerland' },
  { food: 'Wiener Schnitzel', country: 'Austria' },
  { food: 'Apfelstrudel', country: 'Austria' },
  { food: 'Langos', country: 'Hungary' },
  { food: 'Chicken Paprikash', country: 'Hungary' },
  { food: 'Zapiekanka', country: 'Poland' },
  { food: 'Bigos', country: 'Poland' },
  { food: 'Sernik', country: 'Poland' },
  { food: 'Trdelník', country: 'Czech Republic' },
  { food: 'Svíčková', country: 'Czech Republic' },
  { food: 'GulaschsuppeSlovakia287Ćufte', country: 'Bosnia and Herzegovina' },
  { food: 'Ajvar', country: 'North Macedonia' },
  { food: 'Tavë Kosi', country: 'Albania' },
  { food: 'Tarator', country: 'Bulgaria' },
  { food: 'Bakso', country: 'Indonesia' },
  { food: 'Mie Ayam', country: 'Indonesia' },
  { food: 'Soto Betawi', country: 'Indonesia' },
  { food: 'Nasi Uduk', country: 'Indonesia' },
  { food: 'Kuay Teow Soup', country: 'Thailand' },
  { food: 'Khanom Jeen', country: 'Thailand' },
  { food: 'Mi Quang', country: 'Vietnam' },
  { food: 'Bun Bo Hue', country: 'Vietnam' },
  { food: 'Hu Tieu', country: 'Vietnam' },
  { food: 'Nem Nuong', country: 'Vietnam' },
  { food: 'Chicken Adobo', country: 'Philippines' },
  { food: 'Pancit', country: 'Philippines' },
  { food: 'Halo-Halo', country: 'Philippines' },
  { food: 'Bicol Express', country: 'Philippines' },
  { food: 'Tocino', country: 'Philippines' },
  { food: 'Mee Rebus', country: 'Malaysia' },
  { food: 'Curry Laksa', country: 'Malaysia' },
  { food: 'Roti Canai', country: 'Malaysia' },
  { food: 'Asam Laksa', country: 'Malaysia' },
  { food: 'Otak-Otak', country: 'Malaysia' },
  { food: 'Sate Lilit', country: 'Bali' },
  { food: 'Causa', country: 'Peru' },
  { food: 'Anticuchos', country: 'Peru' },
  { food: 'Rocoto Relleno', country: 'Peru' },
  { food: 'Seco de Pollo', country: 'Ecuador' },
  { food: 'Llapingachos', country: 'Ecuador' },
  { food: 'Curanto', country: 'Chile' },
  { food: 'Pastel de Choclo', country: 'Chile' },
  { food: 'Milanesa', country: 'Argentina' },
  { food: 'Provoleta', country: 'Argentina' },
  { food: 'Dulce de Leche', country: 'Argentina' },
  { food: 'Choripán', country: 'Argentina' },
  { food: 'Farofa', country: 'Brazil' },
  { food: 'Coxinha', country: 'Brazil' },
  { food: 'Vatapá', country: 'Brazil' },
  { food: 'Acarajé', country: 'Brazil' },
  { food: 'Feijão Tropeiro', country: 'Brazil' },
  { food: 'Sancocho', country: 'Dominican Republic' },
  { food: 'Mofongo', country: 'Puerto Rico' },
  { food: 'Tostones', country: 'Puerto Rico' },
  { food: 'Callaloo', country: 'Trinidad and Tobago' },
  { food: 'Pepperpot', country: 'Guyana' },
  { food: 'Bake and Shark', country: 'Trinidad and Tobago' },
  { food: 'Johnny Cakes', country: 'Bahamas' },
  { food: 'Conch Fritters', country: 'Bahamas' },
  { food: 'Fried Chicken', country: 'United States' },
  { food: 'Mac and Cheese', country: 'United States' },
  { food: 'Meatloaf', country: 'United States' },
  { food: 'Pulled Pork Sandwich', country: 'United States' },
  { food: 'Philly Cheesesteak', country: 'United States' },
  { food: 'Bagel and Lox', country: 'United States' },
  { food: 'Chicken and Waffles', country: 'United States' },
  { food: 'Biscuits and Gravy', country: 'United States' },
  { food: 'Po\' Boy Sandwich', country: 'United States' },
  { food: 'Deep Dish Pizza', country: 'United States' },
  { food: 'Nanaimo Bars', country: 'Canada' },
  { food: 'Butter Tarts', country: 'Canada' },
  { food: 'BeaverTails', country: 'Canada' },
  { food: 'Split Pea Soup', country: 'Canada' },
  { food: 'Bannock', country: 'Canada' },
  { food: 'Kedgeree', country: 'United Kingdom' },
  { food: 'Scotch Eggs', country: 'United Kingdom' },
  { food: 'Sticky Toffee Pudding', country: 'United Kingdom' },
  { food: 'Cornish Pasty', country: 'England' },
  { food: 'Cullen Skink', country: 'Scotland' },
  { food: 'Cawl', country: 'Wales' },
  { food: 'Boxty', country: 'Ireland' },
  { food: 'Stamppot', country: 'Netherlands' },
  { food: 'Pea Soup', country: 'Netherlands' },
  { food: 'Kroket', country: 'Netherlands' },
  { food: 'Carbonnade Flamande', country: 'Belgium' },
  { food: 'Waterzooi', country: 'Belgium' },
  { food: 'Smushi', country: 'Denmark' },
  { food: 'Æbleskiver', country: 'Denmark' },
  { food: 'Pyttipanna', country: 'Sweden' },
  { food: 'Janssons Frestelse', country: 'Sweden' },
  { food: 'Kjøttkaker', country: 'Norway' },
  { food: 'Salmon Soup', country: 'Finland' },
  { food: 'Cepelinai', country: 'Lithuania' },
  { food: 'Grey Peas with Bacon', country: 'Latvia' },
  { food: 'Verivorst', country: 'Estonia' },
  { food: 'Khorovats', country: 'Armenia' },
  { food: 'Lavash', country: 'Armenia' },
  { food: 'Ash Reshteh', country: 'Iran' },
  { food: 'Tahchin', country: 'Iran' },
  { food: 'Zereshk Polo', country: 'Iran' },
  { food: 'Koobideh', country: 'Iran' },
  { food: 'Chapli Kebab', country: 'Pakistan' },
  { food: 'Sajji', country: 'Pakistan' },
  { food: 'Paya', country: 'Pakistan' },
  { food: 'Pulao', country: 'Pakistan' },
  { food: 'String Hoppers', country: 'Sri Lanka' },
  { food: 'Lamprais', country: 'Sri Lanka' },
  { food: 'Fish Ambul Thiyal', country: 'Sri Lanka' },
  { food: 'Ema Datshi', country: 'Bhutan' },
  { food: 'Jasha Maru', country: 'Bhutan' },
  { food: 'Thenthuk', country: 'Tibet' },
  { food: 'Zhaliang', country: 'China' },
  { food: 'Mapo Tofu', country: 'China' },
  { food: 'Xiaolongbao', country: 'China' },
  { food: 'Chow Mein', country: 'China' },
  { food: 'Mooncakes', country: 'China' },
  { food: 'Roast Goose', country: 'Hong Kong' },
  { food: 'Pineapple Bun', country: 'Hong Kong' },
  { food: 'Pork Chop Bun', country: 'Macau' },
  { food: 'Lu Rou Fan', country: 'Taiwan' },
  { food: 'Scallion Pancake', country: 'Taiwan' },
  { food: 'Tamagoyaki', country: 'Japan' },
  { food: 'Chawanmushi', country: 'Japan' },
  { food: 'Nikujaga', country: 'Japan' },
  { food: 'Curry Udon', country: 'Japan' },
  { food: 'Omurice', country: 'Japan' },
  { food: 'Sundae', country: 'South Korea' },
  { food: 'Kimchi Jjigae', country: 'South Korea' },
  { food: 'Hotteok', country: 'South Korea' },
  { food: 'Bingsu', country: 'South Korea' },
  { food: 'Crab Curry', country: 'Singapore' },
  { food: 'Fish Head Curry', country: 'Singapore' },
  { food: 'Mee Soto', country: 'Singapore' },
  { food: 'Teh Tarik', country: 'Malaysia' },
  { food: 'Nasi Kerabu', country: 'Malaysia' },
  { food: 'Ayam Goreng', country: 'Indonesia' },
  { food: 'Rawon', country: 'Indonesia' },
  { food: 'Sop Buntut', country: 'Indonesia' },
  { food: 'Tinola', country: 'Philippines' },
  { food: 'Laing', country: 'Philippines' },
  { food: 'Kare-Kare', country: 'Philippines' },
  { food: 'Dinuguan', country: 'Philippines' },
  { food: 'Goi Ga', country: 'Vietnam' },
  { food: 'Bun Rieu', country: 'Vietnam' },
  { food: 'Crab Rangoon', country: 'United States' },
  { food: 'Key Lime Pie', country: 'United States' },
  { food: 'Shrimp and Grits', country: 'United States' },
  { food: 'Jambalaya', country: 'United States' },
  { food: 'Chili con Carne', country: 'United States' },
  { food: 'Monte Cristo Sandwich', country: 'United States' },
  { food: 'Pecan Pie', country: 'United States' },
  { food: 'Banana Cream Pie', country: 'United States' },
  { food: 'Hot Dog', country: 'United States' },
  { food: 'Caesar Salad', country: 'Mexico' },
  { food: 'Churro Ice Cream', country: 'Spain' },
  { food: 'Seafood Paella', country: 'Spain' },
  { food: 'Flan', country: 'Spain' },
  { food: 'Leche Flan', country: 'Philippines' },
  { food: 'Horchata', country: 'Mexico' },
  { food: 'Menudo', country: 'Mexico' },
  { food: 'Tlayudas', country: 'Mexico' },
  { food: 'Elote', country: 'Mexico' },
  { food: 'Capirotada', country: 'Mexico' },
  { food: 'Shawarma Plate', country: 'Syria' },
  { food: 'Fatteh', country: 'Syria' },
  { food: 'Mujadara', country: 'Lebanon' },
  { food: 'Kunafa', country: 'Palestine' },
  { food: 'Musakhan', country: 'Palestine' },
  { food: 'Bamia', country: 'Iraq' },
  { food: 'Quzi', country: 'Iraq' },
  { food: 'Machboos', country: 'Kuwait' },
  { food: 'Harees', country: 'United Arab Emirates' },
  { food: 'Camel Burger', country: 'United Arab Emirates' },
  { food: 'Madrouba', country: 'Qatar' },
  { food: 'Ful Medames', country: 'Egypt' },
  { food: 'Molokhia', country: 'Egypt' },
  { food: 'Bissara', country: 'Morocco' },
  { food: 'Chakalaka', country: 'South Africa' },
  { food: 'Vetkoek', country: 'South Africa' },
  { food: 'Pap and Wors', country: 'South Africa' },
  { food: 'Ofe Nsala', country: 'Nigeria' },
  { food: 'Akara', country: 'Nigeria' },
  { food: 'Kenkey', country: 'Ghana' },
  { food: 'Banku', country: 'Ghana' },
  { food: 'Isombe', country: 'Rwanda' },
  { food: 'Brochettes', country: 'Rwanda' },
  { food: 'Ugali', country: 'Kenya' },
  { food: 'Pilau Rice', country: 'Tanzania' },
  { food: 'Rolex', country: 'Uganda' },
  { food: 'Cachupa', country: 'Cape Verde' },
  { food: 'Bourek', country: 'Algeria' },
  { food: 'Mechoui', country: 'Algeria' },
  { food: 'Lablabi', country: 'Tunisia' },
  { food: 'Chakchouka', country: 'Tunisia' },
  { food: 'Pide', country: 'Turkey' },
  { food: 'Menemen', country: 'Turkey' },
  { food: 'Iskender Kebab', country: 'Turkey' },
  { food: 'Künefe', country: 'Turkey' },
  { food: 'Adana Kebab', country: 'Turkey' },
  { food: 'Manti', country: 'Turkey' },
  { food: 'Lokum', country: 'Turkey' },
  { food: 'Spanakopita', country: 'Greece' },
  { food: 'Fasolada', country: 'Greece' },
  { food: 'Kleftiko', country: 'Greece' },
  { food: 'Loukoumades', country: 'Greece' },
  { food: 'Caldo Verde', country: 'Portugal' },
  { food: 'Bifana', country: 'Portugal' },
  { food: 'Irish Soda Bread', country: 'Ireland' },
  { food: 'Black Pudding', country: 'Ireland' },
  { food: 'Frikandel', country: 'Netherlands' },
  { food: 'Smalahove', country: 'Norway' },
  { food: 'Leipäjuusto', country: 'Finland' },
  { food: 'Kanelbullar', country: 'Sweden' },
  { food: 'Medovik', country: 'Russia' },
  { food: 'Syrniki', country: 'Russia' },
  { food: 'Banitsa', country: 'Bulgaria' },
  { food: 'Peka', country: 'Croatia' },
  { food: 'Punjene Paprike', country: 'Serbia' },
  { food: 'Tufahija', country: 'Bosnia and Herzegovina' },
  { food: 'Fërgesë', country: 'Albania' },
  { food: 'Tavuk Göğsü', country: 'Turkey' },
  { food: 'Kulajda', country: 'Czech Republic' },
  { food: 'Bryndzové Halušky', country: 'Slovakia' },
  { food: 'Potato Pancakes', country: 'Belarus' },
];
