export type TestimonialAccent = "gold" | "paprika" | "sage";

export type Testimonial = {
  quote: string;
  name: string;
  role: string;
  initials: string;
  accent: TestimonialAccent;
};

const ACCENTS: TestimonialAccent[] = ["gold", "paprika", "sage"];

const RAW: Omit<Testimonial, "accent" | "initials">[] = [
  { quote: "I had three sad ingredients in my fridge and ended up making the best stir-fry of my life. This app is my new best friend.", name: "Priya M.", role: "Home cook · London" },
  { quote: "Finally — a recipe app that doesn't bury the recipe under a life story. Type a dish, get a real recipe. That's it.", name: "Marco D.", role: "Weeknight dad · Milan" },
  { quote: "I cook from 8 countries in a week now. My partner thinks I went to culinary school in secret.", name: "Jess K.", role: "Curious eater · Brooklyn" },
  { quote: "Pantry mode is genius. Half an onion, leftover rice, one egg — and somehow dinner. No grocery run, no guilt.", name: "Aisha R.", role: "Grad student · Toronto" },
  { quote: "My kid is gluten-free and I'm out of ideas by Tuesday. This thing rescued my whole week — twice.", name: "Daniel O.", role: "Dad of two · Austin" },
  { quote: "I asked for 'something my Sicilian grandmother would approve of' and it actually delivered. I'm a little emotional.", name: "Elena V.", role: "Food writer · Lisbon" },
  { quote: "11pm, starving, three things in the fridge. Thirty seconds later I'm eating shakshuka. This shouldn't be legal.", name: "Sam T.", role: "Night owl · Berlin" },
  { quote: "I travel a lot and I miss the food. Typing 'Hanoi street breakfast' and getting it right — that's the magic.", name: "Noor A.", role: "Designer · Dubai" },
  { quote: "I cancelled two recipe subscriptions. No ads, no scrolling past someone's divorce — just dinner. Perfect.", name: "Hiro K.", role: "Engineer · Osaka" },
  { quote: "I'm a terrible cook. Was. Past tense. My roommates noticed first.", name: "Lena F.", role: "Student · Amsterdam" },
  { quote: "Asked it for Oaxacan mole the way my abuela makes it. It got close enough that I called her crying.", name: "Diego R.", role: "Architect · Mexico City" },
  { quote: "Saved me three takeout orders this week. That's basically the subscription paying for itself.", name: "Olivia P.", role: "Consultant · Chicago" },
  { quote: "I batch-cook every Sunday and this app gave me a rotation I actually look forward to.", name: "Femi A.", role: "Nurse · Lagos" },
  { quote: "My partner is vegan, I'm not. The 'cook one base, split two ways' suggestions are chef's kiss.", name: "Tom B.", role: "Software dev · Sydney" },
  { quote: "I asked for a romantic three-course menu under €25. It delivered. The date went well too.", name: "Camille L.", role: "Photographer · Paris" },
  { quote: "Korean banchan, real ones, not the influencer version. I'm impressed.", name: "Min-jun S.", role: "Designer · Seoul" },
  { quote: "I have a tiny kitchen and one pan. The 'one-pan' filter is the most honest filter on the internet.", name: "Anya V.", role: "Writer · Prague" },
  { quote: "I cooked Ethiopian doro wat for friends and they asked where I bought it. From my own stove, thanks.", name: "Bisrat M.", role: "Product manager · Addis Ababa" },
  { quote: "30 minutes, four ingredients, my mother-in-law asking for the recipe. Marriage saved.", name: "Rahul S.", role: "Banker · Mumbai" },
  { quote: "I'm 67 and not great with apps. Even I get this one. Big print on the recipe helped.", name: "Margaret O.", role: "Retired teacher · Edinburgh" },
  { quote: "Tried 'cozy Sunday' as a vibe. Got a slow-cooked ragu that took over my apartment in the best way.", name: "Sofia G.", role: "Illustrator · Barcelona" },
  { quote: "My grocery bill dropped 30% because I actually use what's in my fridge now.", name: "Kwame B.", role: "Teacher · Accra" },
  { quote: "I asked for 'something my dad would call real food.' Got steak frites. Dad approved.", name: "Hannah W.", role: "Marketing · Toronto" },
  { quote: "The recipes scale properly. Cooking for 9 didn't break it. Cooking for 1 didn't either.", name: "Pavel D.", role: "Chef · Warsaw" },
  { quote: "Late-night ramen suggestions changed my whole month.", name: "Yuki T.", role: "Animator · Tokyo" },
  { quote: "I gave it 'leftover Thanksgiving turkey day 4' and got three things I'd actually want to eat.", name: "Brian H.", role: "Engineer · Denver" },
  { quote: "Indian regional cooking that doesn't pretend everything is butter chicken. Finally.", name: "Anjali K.", role: "Doctor · Bangalore" },
  { quote: "I asked for 'fancy without being fussy.' Got coq au vin. Felt like a grown-up.", name: "Lucas M.", role: "Lawyer · Montreal" },
  { quote: "Asked it to teach me sourdough basics. It actually taught me, didn't just throw a recipe at me.", name: "Greta H.", role: "Architect · Copenhagen" },
  { quote: "I host dinner parties more often because planning takes ten minutes now.", name: "Ines C.", role: "Producer · Madrid" },
  { quote: "Filipino adobo, the real chicken-and-pork kind. I'm not even Filipino and I cried.", name: "Tony Z.", role: "Photographer · Manila" },
  { quote: "Diabetic-friendly suggestions that don't taste like punishment. Underrated win.", name: "Carla J.", role: "Accountant · Houston" },
  { quote: "I keep meaning to cancel my meal-kit and this is finally the push.", name: "Eric N.", role: "Designer · Stockholm" },
  { quote: "My kid is the world's pickiest eater. We have a working rotation of 12 meals now. Twelve!", name: "Susan P.", role: "Mom of three · Atlanta" },
  { quote: "Argentinian asado tips that actually respect the meat. I was skeptical and I was wrong.", name: "Mateo F.", role: "Wine importer · Buenos Aires" },
  { quote: "Cooking after a 12-hour shift is the worst. This app makes it a 25-minute thing.", name: "Rachel D.", role: "ER nurse · Manchester" },
  { quote: "Asked for Lebanese mezze for 8 people, $40 budget. Came in at $36 and looked like a feast.", name: "Layla H.", role: "Translator · Beirut" },
  { quote: "I trust it more than the top three Google results combined. Way less SEO sludge.", name: "Owen K.", role: "Writer · Dublin" },
  { quote: "Plant-based for ethics, not for vibes. The recipes here treat it like real food, not a substitute.", name: "Maya G.", role: "Researcher · Berlin" },
  { quote: "My boyfriend now says 'should we ask the fridge?' instead of 'should we order in.' Game changed.", name: "Zoe R.", role: "Editor · London" },
  { quote: "Cypriot stuffed vine leaves. Mine. From my own kitchen. I'm shaking.", name: "Andreas P.", role: "Teacher · Nicosia" },
  { quote: "I'm celiac and the substitutions are smart, not desperate. Real difference.", name: "Hannah V.", role: "Lawyer · Auckland" },
  { quote: "Asked for 'something to impress a Michelin-chef friend.' It made me make miso-cured cod. Friend was impressed.", name: "Ravi P.", role: "Investor · Singapore" },
  { quote: "It taught me knife skills inside the recipe instead of pointing at a YouTube video. Small thing, huge.", name: "Clara M.", role: "Junior cook · Lyon" },
  { quote: "I'm a divorced dad and 'what do I cook for the kids this weekend' used to ruin my Friday. Not anymore.", name: "Mark T.", role: "Real estate · Toronto" },
  { quote: "I run a small B&B and it helps me build seasonal breakfast menus in like five minutes.", name: "Beatrice R.", role: "Innkeeper · Tuscany" },
  { quote: "Asked for budget protein meals while bulking. Actually understood macros, didn't just push chicken breast.", name: "Jared L.", role: "PT · Los Angeles" },
  { quote: "Cooking for one without making seven days of leftovers is harder than it sounds. This nailed it.", name: "Ingrid B.", role: "Architect · Oslo" },
  { quote: "Persian rice with the proper tahdig. The crispy bottom. I'm crying again.", name: "Shirin K.", role: "Engineer · Tehran" },
  { quote: "My partner has reflux and a list of nope-foods. The app remembered. That was the moment for me.", name: "Patrick S.", role: "Accountant · Glasgow" },
  { quote: "I asked for 'comfort food but not heavy.' Got a creamy mushroom orzo that hit perfectly.", name: "Naomi F.", role: "Therapist · Vancouver" },
  { quote: "Thai grandmother level. I am not exaggerating. I called my mom mid-bite.", name: "Pim C.", role: "Designer · Bangkok" },
  { quote: "I have ADHD and decision fatigue at 6pm is real. This removes the worst step.", name: "Charlie B.", role: "Copywriter · Brighton" },
  { quote: "Cuban ropa vieja. Authentic. Better than the Miami place I used to swear by.", name: "Lourdes P.", role: "Realtor · Miami" },
  { quote: "I'm a chef and I still use it for inspiration on my nights off. That's the highest compliment I can give.", name: "Mateusz K.", role: "Head chef · Krakow" },
  { quote: "The shopping lists are clean and grouped by section. Whoever designed that — thank you.", name: "Erica J.", role: "Mom · Seattle" },
  { quote: "I asked it to plan a week of Mediterranean-ish meals. The plan actually worked. Variety, leftovers, the whole thing.", name: "Theo A.", role: "Pilot · Athens" },
  { quote: "Vietnamese pho with the right depth of broth. I gasped.", name: "Linh N.", role: "Marketer · Hanoi" },
  { quote: "I'm pregnant, exhausted, and tired of every food I used to love. This helped me find new ones.", name: "Anna B.", role: "Designer · Helsinki" },
  { quote: "Asked for 'high protein, low effort, not boring.' Got harissa salmon bowls. New staple.", name: "Drew R.", role: "Engineer · Austin" },
  { quote: "I cook for my elderly mom and her taste is specific. The app adapted after two corrections.", name: "Selma G.", role: "Caregiver · Istanbul" },
  { quote: "South Indian dosa with proper fermentation guidance. I've tried 12 recipes online. This one worked.", name: "Karthik V.", role: "Engineer · Chennai" },
  { quote: "My partner does keto. I don't. We finally cook the same dinner with smart swaps.", name: "Madison T.", role: "Teacher · Phoenix" },
  { quote: "Asked for Hungarian goulash like a proper one. Got a recipe my grandma would nod at.", name: "Bence H.", role: "Carpenter · Budapest" },
  { quote: "I batch-cook for the homeless shelter on Sundays. The 'scale to 40' feature is unreal.", name: "Father Ben K.", role: "Volunteer · Dublin" },
  { quote: "I asked for 'breakfast for dinner but elegant.' Got dutch baby with caramelized pears. Dating myself, frankly.", name: "Quinn M.", role: "Writer · Portland" },
  { quote: "Moroccan tagine that respected the spices. Didn't dumb it down. I felt seen.", name: "Yasmine T.", role: "Architect · Casablanca" },
  { quote: "Three things in the freezer, $0 to spend. Got dinner. Got dignity.", name: "Devon L.", role: "Student · Detroit" },
  { quote: "I have arthritis and 'how do I do this without gripping' tweaks made cooking possible again.", name: "Maureen R.", role: "Retired nurse · Cardiff" },
  { quote: "I asked for 'New Orleans gumbo, don't disrespect it.' It didn't. Roux instructions were perfect.", name: "Calvin B.", role: "Musician · New Orleans" },
  { quote: "I cook with my 6-year-old. The kid-safe step suggestions are actually thoughtful.", name: "Imogen H.", role: "Mom of one · Wellington" },
  { quote: "I work nights and 'breakfast at 3am that doesn't suck' is a category I never knew I needed.", name: "Petra O.", role: "ER doctor · Vienna" },
  { quote: "Asked for a Georgian khachapuri. Got the boat-shaped one with the runny egg. I am not the same person.", name: "Nino K.", role: "Translator · Tbilisi" },
  { quote: "I run a vegan supper club. The substitutions library here is the best I've used. Period.", name: "Greer L.", role: "Chef · Portland" },
  { quote: "Brazilian moqueca with proper dendê oil swap because I couldn't find any. Smart suggestion.", name: "Beatriz F.", role: "Engineer · São Paulo" },
  { quote: "I'm a college student with a hot plate and a microwave. The 'no real kitchen' filter is my best friend.", name: "Casey W.", role: "Undergrad · Boston" },
  { quote: "I asked for 'romantic, low-effort, will impress.' Got pan-seared scallops with brown butter. Won the night.", name: "Jonas E.", role: "Architect · Hamburg" },
  { quote: "It corrected my technique mid-recipe when I said the onions weren't browning. That's coaching, not just a recipe.", name: "Halle A.", role: "Designer · Reykjavik" },
  { quote: "Lebanese kibbeh nayyeh — I asked for tradition, not pasteurized fear. It respected the request.", name: "Rami N.", role: "Doctor · Beirut" },
  { quote: "I cooked Burmese mohinga for the first time. Ten years of wanting to. It happened today.", name: "Su Su L.", role: "Teacher · Yangon" },
  { quote: "My doctor said cut sodium. The app rebuilt my whole rotation in one evening.", name: "Bernard H.", role: "Retired engineer · Manchester" },
  { quote: "I asked for 'autumn, candle-lit, makes the house smell amazing.' Got cider-braised pork. Yes.", name: "Naila R.", role: "Editor · Karachi" },
  { quote: "Cooking for shabbat went from stressful to a joy. The timing suggestions are gold.", name: "Esther B.", role: "Mom · Tel Aviv" },
  { quote: "I asked for 'cheap, fast, will love myself tomorrow.' Got chickpea curry. Loved myself.", name: "Henry J.", role: "Bartender · Liverpool" },
  { quote: "Polish pierogi from scratch with my partner. Took an afternoon. Made a memory.", name: "Aleks K.", role: "Engineer · Wrocław" },
  { quote: "My anxiety drops the second I stop scrolling for a recipe. This app is a 30-second decision.", name: "Tamsin O.", role: "Therapist · Bristol" },
  { quote: "I asked for 'Thanksgiving for 14, two vegetarians, one gluten-free.' Got a full plan that worked.", name: "Wendy D.", role: "Mom · Connecticut" },
  { quote: "Senegalese thieboudienne. Real one. I'm so happy.", name: "Aminata D.", role: "Journalist · Dakar" },
  { quote: "I asked for a dish from a country I'd never cooked from. Got Trinidadian doubles. Mind blown.", name: "Marcus E.", role: "Engineer · London" },
  { quote: "It quietly remembers I hate cilantro. Every time. That's the future.", name: "Beth A.", role: "Designer · San Francisco" },
  { quote: "I asked for 'quiet Sunday, just me, something a little fancy.' Got mushroom risotto. Romanticized my own life.", name: "Iris K.", role: "Writer · Ghent" },
  { quote: "Chinese home cooking that wasn't 'westernized.' Mapo tofu the way it should be.", name: "Wei L.", role: "Engineer · Shanghai" },
  { quote: "I asked for 'feed 6 picky teenagers, no leftovers, under $30.' Mission accomplished, three times now.", name: "Trish M.", role: "Foster parent · Calgary" },
  { quote: "Catalan calçots in February. I'm in Toronto. It improvised the sauce beautifully.", name: "Pol R.", role: "Architect · Toronto" },
  { quote: "I asked it to teach me to make stock from scratch. Three weeks later, I'm a stock person now.", name: "Helene F.", role: "Mom · Marseille" },
  { quote: "Bosnian ćevapi with the proper somun bread suggestion. Felt like Sarajevo for a night.", name: "Edin H.", role: "Driver · Sarajevo" },
  { quote: "I'm a single dad. 'What's in the fridge plus 3 things I always have' is the most useful prompt of my life.", name: "Ryan O.", role: "Dad · Edmonton" },
  { quote: "Spent 20 years afraid of frying fish. App walked me through it. I have transcended.", name: "Glenda P.", role: "Retired · Cape Town" },
  { quote: "Asked for 'Persian rice for someone scared of Persian rice.' It coached me. The tahdig appeared.", name: "Sara K.", role: "Designer · Tehran" },
  { quote: "Cambodian fish amok. I needed substitutions and it nailed them. Took me right back.", name: "Sopheap M.", role: "NGO worker · Phnom Penh" },
  { quote: "I have a $300 grocery budget for a family of five. The weekly planner respects it. Religiously.", name: "Tanya S.", role: "Mom · Memphis" },
  { quote: "It taught me what 'finish with acid' meant in three sentences. I'm a better cook for it.", name: "Wilson R.", role: "Engineer · Pittsburgh" },
  { quote: "I am 22 and live alone in a new city. This app feels like having a parent in the kitchen.", name: "Jin L.", role: "Intern · Frankfurt" },
  { quote: "Asked for 'fancy Friday for my husband's birthday, $50 budget.' Got duck à l'orange. He cried.", name: "Maya O.", role: "Teacher · Nairobi" },
  { quote: "Even the way it explains substitutions is calm. I never feel judged for not having sherry vinegar.", name: "Pedro V.", role: "Engineer · Porto" },
  { quote: "I went from 'I can't cook' to hosting brunch for 8. Six months. This is genuinely life-changing.", name: "Alyssa W.", role: "Sales · Nashville" },
];

function initialsFor(name: string): string {
  const parts = name.replace(/[^A-Za-z .]/g, "").split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "??";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

export const TESTIMONIALS: Testimonial[] = RAW.map((t, i) => ({
  ...t,
  initials: initialsFor(t.name),
  accent: ACCENTS[i % ACCENTS.length],
}));