/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChefsRouteImport } from './routes/chefs'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as ShopRecipeIdRouteImport } from './routes/shop.$recipeId'
import { Route as SharedSlugRouteImport } from './routes/shared.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CommunityRecipeIdRouteImport } from './routes/community.$recipeId'
import { Route as ChefUsernameRouteImport } from './routes/chef.$username'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedMyRecipesRouteImport } from './routes/_authenticated/my-recipes'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedCookbooksRouteImport } from './routes/_authenticated/cookbooks'
import { Route as AuthenticatedCookbookRouteImport } from './routes/_authenticated/cookbook'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ShopCookbookCookbookIdRouteImport } from './routes/shop.cookbook.$cookbookId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AuthenticatedCookIdRouteImport } from './routes/_authenticated/cook.$id'
import { Route as AuthenticatedCommunityNewRouteImport } from './routes/_authenticated/community.new'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminQuotaRouteImport } from './routes/_authenticated/admin.quota'
import { Route as AuthenticatedAdminAbuseRouteImport } from './routes/_authenticated/admin.abuse'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsRoute = ChefsRouteImport.update({
  id: '/chefs',
  path: '/chefs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRecipeIdRoute = ShopRecipeIdRouteImport.update({
  id: '/shop/$recipeId',
  path: '/shop/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedSlugRoute = SharedSlugRouteImport.update({
  id: '/shared/$slug',
  path: '/shared/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRecipeIdRoute = CommunityRecipeIdRouteImport.update({
  id: '/community/$recipeId',
  path: '/community/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefUsernameRoute = ChefUsernameRouteImport.update({
  id: '/chef/$username',
  path: '/chef/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyRecipesRoute = AuthenticatedMyRecipesRouteImport.update({
  id: '/my-recipes',
  path: '/my-recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCookbooksRoute = AuthenticatedCookbooksRouteImport.update({
  id: '/cookbooks',
  path: '/cookbooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCookbookRoute = AuthenticatedCookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopCookbookCookbookIdRoute = ShopCookbookCookbookIdRouteImport.update({
  id: '/shop/cookbook/$cookbookId',
  path: '/shop/cookbook/$cookbookId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCookIdRoute = AuthenticatedCookIdRouteImport.update({
  id: '/cook/$id',
  path: '/cook/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityNewRoute =
  AuthenticatedCommunityNewRouteImport.update({
    id: '/community/new',
    path: '/community/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminQuotaRoute = AuthenticatedAdminQuotaRouteImport.update({
  id: '/admin/quota',
  path: '/admin/quota',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAbuseRoute = AuthenticatedAdminAbuseRouteImport.update({
  id: '/admin/abuse',
  path: '/admin/abuse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chefs': typeof ChefsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/cookbook': typeof AuthenticatedCookbookRoute
  '/cookbooks': typeof AuthenticatedCookbooksRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/my-recipes': typeof AuthenticatedMyRecipesRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/sell': typeof AuthenticatedSellRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/community/$recipeId': typeof CommunityRecipeIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shared/$slug': typeof SharedSlugRoute
  '/shop/$recipeId': typeof ShopRecipeIdRoute
  '/community/': typeof CommunityIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/admin/quota': typeof AuthenticatedAdminQuotaRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/cook/$id': typeof AuthenticatedCookIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/cookbook/$cookbookId': typeof ShopCookbookCookbookIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chefs': typeof ChefsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/cookbook': typeof AuthenticatedCookbookRoute
  '/cookbooks': typeof AuthenticatedCookbooksRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/my-recipes': typeof AuthenticatedMyRecipesRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/sell': typeof AuthenticatedSellRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/community/$recipeId': typeof CommunityRecipeIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shared/$slug': typeof SharedSlugRoute
  '/shop/$recipeId': typeof ShopRecipeIdRoute
  '/community': typeof CommunityIndexRoute
  '/shop': typeof ShopIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/admin/quota': typeof AuthenticatedAdminQuotaRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/cook/$id': typeof AuthenticatedCookIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/cookbook/$cookbookId': typeof ShopCookbookCookbookIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/chefs': typeof ChefsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/cookbook': typeof AuthenticatedCookbookRoute
  '/_authenticated/cookbooks': typeof AuthenticatedCookbooksRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/my-recipes': typeof AuthenticatedMyRecipesRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/community/$recipeId': typeof CommunityRecipeIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shared/$slug': typeof SharedSlugRoute
  '/shop/$recipeId': typeof ShopRecipeIdRoute
  '/community/': typeof CommunityIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/_authenticated/admin/quota': typeof AuthenticatedAdminQuotaRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/community/new': typeof AuthenticatedCommunityNewRoute
  '/_authenticated/cook/$id': typeof AuthenticatedCookIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/cookbook/$cookbookId': typeof ShopCookbookCookbookIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chefs'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/analytics'
    | '/cookbook'
    | '/cookbooks'
    | '/earnings'
    | '/my-recipes'
    | '/plan'
    | '/pricing'
    | '/sell'
    | '/usage'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/chef/$username'
    | '/community/$recipeId'
    | '/email/unsubscribe'
    | '/shared/$slug'
    | '/shop/$recipeId'
    | '/community/'
    | '/shop/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/abuse'
    | '/admin/quota'
    | '/admin/usage'
    | '/community/new'
    | '/cook/$id'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/shop/cookbook/$cookbookId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chefs'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/analytics'
    | '/cookbook'
    | '/cookbooks'
    | '/earnings'
    | '/my-recipes'
    | '/plan'
    | '/pricing'
    | '/sell'
    | '/usage'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/chef/$username'
    | '/community/$recipeId'
    | '/email/unsubscribe'
    | '/shared/$slug'
    | '/shop/$recipeId'
    | '/community'
    | '/shop'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/abuse'
    | '/admin/quota'
    | '/admin/usage'
    | '/community/new'
    | '/cook/$id'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/shop/cookbook/$cookbookId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/chefs'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/_authenticated/analytics'
    | '/_authenticated/cookbook'
    | '/_authenticated/cookbooks'
    | '/_authenticated/earnings'
    | '/_authenticated/my-recipes'
    | '/_authenticated/plan'
    | '/_authenticated/pricing'
    | '/_authenticated/sell'
    | '/_authenticated/usage'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/chef/$username'
    | '/community/$recipeId'
    | '/email/unsubscribe'
    | '/shared/$slug'
    | '/shop/$recipeId'
    | '/community/'
    | '/shop/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/abuse'
    | '/_authenticated/admin/quota'
    | '/_authenticated/admin/usage'
    | '/_authenticated/community/new'
    | '/_authenticated/cook/$id'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/shop/cookbook/$cookbookId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChefsRoute: typeof ChefsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ChefUsernameRoute: typeof ChefUsernameRoute
  CommunityRecipeIdRoute: typeof CommunityRecipeIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SharedSlugRoute: typeof SharedSlugRoute
  ShopRecipeIdRoute: typeof ShopRecipeIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ShopCookbookCookbookIdRoute: typeof ShopCookbookCookbookIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs': {
      id: '/chefs'
      path: '/chefs'
      fullPath: '/chefs'
      preLoaderRoute: typeof ChefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$recipeId': {
      id: '/shop/$recipeId'
      path: '/shop/$recipeId'
      fullPath: '/shop/$recipeId'
      preLoaderRoute: typeof ShopRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$slug': {
      id: '/shared/$slug'
      path: '/shared/$slug'
      fullPath: '/shared/$slug'
      preLoaderRoute: typeof SharedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$recipeId': {
      id: '/community/$recipeId'
      path: '/community/$recipeId'
      fullPath: '/community/$recipeId'
      preLoaderRoute: typeof CommunityRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$username': {
      id: '/chef/$username'
      path: '/chef/$username'
      fullPath: '/chef/$username'
      preLoaderRoute: typeof ChefUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-recipes': {
      id: '/_authenticated/my-recipes'
      path: '/my-recipes'
      fullPath: '/my-recipes'
      preLoaderRoute: typeof AuthenticatedMyRecipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cookbooks': {
      id: '/_authenticated/cookbooks'
      path: '/cookbooks'
      fullPath: '/cookbooks'
      preLoaderRoute: typeof AuthenticatedCookbooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cookbook': {
      id: '/_authenticated/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof AuthenticatedCookbookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cookbook/$cookbookId': {
      id: '/shop/cookbook/$cookbookId'
      path: '/shop/cookbook/$cookbookId'
      fullPath: '/shop/cookbook/$cookbookId'
      preLoaderRoute: typeof ShopCookbookCookbookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cook/$id': {
      id: '/_authenticated/cook/$id'
      path: '/cook/$id'
      fullPath: '/cook/$id'
      preLoaderRoute: typeof AuthenticatedCookIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/new': {
      id: '/_authenticated/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof AuthenticatedCommunityNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/quota': {
      id: '/_authenticated/admin/quota'
      path: '/admin/quota'
      fullPath: '/admin/quota'
      preLoaderRoute: typeof AuthenticatedAdminQuotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/abuse': {
      id: '/_authenticated/admin/abuse'
      path: '/admin/abuse'
      fullPath: '/admin/abuse'
      preLoaderRoute: typeof AuthenticatedAdminAbuseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCookbookRoute: typeof AuthenticatedCookbookRoute
  AuthenticatedCookbooksRoute: typeof AuthenticatedCookbooksRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedMyRecipesRoute: typeof AuthenticatedMyRecipesRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedAdminAbuseRoute: typeof AuthenticatedAdminAbuseRoute
  AuthenticatedAdminQuotaRoute: typeof AuthenticatedAdminQuotaRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedCommunityNewRoute: typeof AuthenticatedCommunityNewRoute
  AuthenticatedCookIdRoute: typeof AuthenticatedCookIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCookbookRoute: AuthenticatedCookbookRoute,
  AuthenticatedCookbooksRoute: AuthenticatedCookbooksRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedMyRecipesRoute: AuthenticatedMyRecipesRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedAdminAbuseRoute: AuthenticatedAdminAbuseRoute,
  AuthenticatedAdminQuotaRoute: AuthenticatedAdminQuotaRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedCommunityNewRoute: AuthenticatedCommunityNewRoute,
  AuthenticatedCookIdRoute: AuthenticatedCookIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChefsRoute: ChefsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ChefUsernameRoute: ChefUsernameRoute,
  CommunityRecipeIdRoute: CommunityRecipeIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SharedSlugRoute: SharedSlugRoute,
  ShopRecipeIdRoute: ShopRecipeIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ShopCookbookCookbookIdRoute: ShopCookbookCookbookIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
